package erenik.evergreen.common.player;

/**
 * Created by Emil on 2016-10-31.
 */
public enum Stat {
    ID(0), // Should be generated by server on start. 0 for localhost player.
    TurnPlayed(0),
    TurnSurvived(0),
    /// Config stats.
    Difficulty(0), // 0 - Easiest, 10% progress lost upon death (all stats n skills). 1 - Easy, 20%, 2 - Medium, 35% loss, 3 - Hard, 50% loss, 4 - Unforgiving, 75% loss. 5 - Wipeout, 100%, hardcore
    RunAway(0.25f), // Default HP-percentage when the player wants to run for his/her life to survive combats (if applicable).
    /// Current stats.
    Lives(5), // Lives, depends on difficulty. Counts down on each KO.
    HP(10), MAX_HP(10),
    FOOD(5), FoodHotspot(0),
    MATERIALS(3), MaterialDepot(0),
    BASE_ATTACK(10), ATTACK_BONUS(0), // Attack and defense bonuses, based on? Permanent increases? Also later...?
    BASE_DEFENSE(10), DEFENSE_BONUS(0), // Base defense, i.e. 10? Might vary in the future based on difficulty?
    SHELTER_DEFENSE(1), SHELTER_DEFENSE_PROGRESS(0), // Level and progress towards next level.
    SPEED(1),
    EMISSIONS(0),
    ABANDONED_SHELTER(0), // Abandoned shelters to explore! Own event for it.
    RANDOM_PLAYERS_SHELTERS(0),  // Random player shelters to be randomly allocated shortly (ask server to whom it belongs?) or postpone until later.
    ENEMY_STRONGHOLDS(0), // Enemy strongholds that you've found.
    UNALLOCATED_EXP(20), // Free exp to be distributed among any skill when the player pleases.
    CurrentTransport(-1),
    RandomPlayerFound(0), // Random player to be found. Requires connection to server to get which one you find.
    ;

    Stat(float defaultValue)
    {
        this.defaultValue = defaultValue;
    }
    public float defaultValue;
}
